### ISSUE TITLE
windows dll error jupyter notebook

### ISSUE THREAD

**Issue by anou85** [modsim/CADET-Match#15]
Hi, 
I've been trying to get the cadet installation working on Windows. However, when I run the "verify CADET is working correctly" cell in the Jupyter notebook, I get:

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-c383e128f97d> in <module>
     13 
     14 #scientific library for python
---> 15 import scipy
     16 
     17 #pandas is python library for data analysis

~\AppData\Roaming\Python\Python37\site-packages\scipy\__init__.py in <module>
    102 
    103 # Allow distributors to run custom init code
--> 104 from . import _distributor_init
    105 
    106 __all__ += _num.__all__

~\AppData\Roaming\Python\Python37\site-packages\scipy\_distributor_init.py in <module>
     59             os.chdir(libs_path)
     60             for filename in glob.glob(os.path.join(libs_path, '*dll')):
---> 61                 WinDLL(os.path.abspath(filename))
     62         finally:
     63             os.chdir(owd)

~\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: [WinError 126] The specified module could not be found

`
I don't know which of the filenames could be the offending one, or how to solve this issue. 
Any pointers?

Cheers,
Anja

**Comment by Immudzen** [comment]
This is a really odd error. It looks like the system is failing when it tries to import scipy which is a basic python library and ships with Anaconda. 

Unless you are using Anaconda for something else what I would suggest is to just uninstall and reinstall Anaconda since it seems something it is has been damaged.

After that has been done open up Anaconda Navigator and then click on environments. 

In there on the base (root) click on the green arrow and open terminal
type 

conda update --all

and hit enter

Then run

pip install CADETMatch

and hit enter

Everything should work. If you run into any problems let me know and I will work on some better install instructions. I am not sure why the ones we used during the tutorial are not working but maybe a library changed that is causing a problem.

**Comment by anou85** [comment]
Hi, thank you for your suggestion. However, I'm using scipy and numpy in other notebooks and its working fine. I think its the WinDLL function which is calling the dll files in the specified path. One of those files seems to have a problem

**Comment by Immudzen** [comment]
I have looked through the code and I can't find any explanation for the
problem.

The error is not related to CADET and there are no CADET libraries in the
traceback. The problem is importing scipy. CADETMatch makes no changes to
scipy nor does it change any of the python search paths or module loading.

From what I can see there are similar issues reported where Anaconda gets
damaged. https://github.com/conda/conda/issues/9313  and
https://github.com/conda/conda/issues/8836

**Comment by anou85** [comment]
Hi, it wasn't conda but the VCRUNTIME140_1.dll. I somehow got en error message pointing to the interferring dll, a re-installation of Microsoft Visualstudio solved the problem, and cadet and cadet-match are running smoothly. Thank you!

**Comment by Immudzen** [comment]
Wow that is a weird problem. I would not have expected that one. Good job
tracking it down and let me know if you need any help.
